# Generated by Django 3.0.3 on 2020-03-12 00:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200307_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_datetime', models.DateTimeField(default=datetime.datetime(2020, 3, 12, 0, 22, 15, 133856, tzinfo=utc))),
                ('checkout_datetime', models.DateTimeField(default=datetime.datetime(2020, 3, 12, 0, 22, 15, 133856, tzinfo=utc))),
                ('phone_number', models.CharField(max_length=20)),
                ('parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.Parking')),
            ],
        ),
    ]
