# Generated by Django 3.0.3 on 2020-03-12 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200311_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='checkin_datetime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='checkout_datetime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='checkin_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='checkin_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='checkout_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='checkout_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
