# Generated by Django 3.0.3 on 2020-04-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200312_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
