# Generated by Django 3.0.3 on 2020-04-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_schedule_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='confirmation_code',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
